# Generated by Django 5.2.16 on 2026-08-28 22:22

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0008_alter_toolunit_status'),
        ('customers', '0001_initial'),
        ('organizations', '0002_establishment'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField(verbose_name='início contratado')),
                ('ends_at', models.DateTimeField(verbose_name='fim contratado')),
                ('total_amount_snapshot', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='valor total contratado')),
                ('customer_name_snapshot', models.CharField(max_length=200, verbose_name='nome do cliente')),
                ('customer_document_snapshot', models.CharField(blank=True, max_length=20, verbose_name='documento do cliente')),
                ('status', models.CharField(choices=[('PREPARED', 'Preparado'), ('ACTIVE', 'Em andamento'), ('COMPLETED', 'Concluído')], default='PREPARED', max_length=10, verbose_name='situação')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='retirada concluída em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='devolução concluída em')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='customers.customer')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='organizations.establishment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='organizations.organization')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'contrato',
                'verbose_name_plural': 'contratos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_code_snapshot', models.CharField(max_length=50, verbose_name='código do equipamento')),
                ('tool_name_snapshot', models.CharField(max_length=260, verbose_name='ferramenta')),
                ('checked_out_at', models.DateTimeField(blank=True, null=True, verbose_name='retirada em')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='devolvida em')),
                ('return_condition', models.CharField(blank=True, choices=[('AVAILABLE', 'Apta para locação'), ('INSPECTION', 'Em inspeção'), ('MAINTENANCE', 'Em manutenção'), ('DAMAGED', 'Danificada'), ('LOST', 'Perdida')], max_length=16, verbose_name='condição na devolução')),
                ('return_notes', models.TextField(blank=True, verbose_name='observações da devolução')),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checked_out_contract_items', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contracts.contract')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_items', to='organizations.organization')),
                ('reservation_allocation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contract_item', to='reservations.reservationallocation')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returned_contract_items', to=settings.AUTH_USER_MODEL)),
                ('tool_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_items', to='catalog.toolunit')),
            ],
            options={
                'verbose_name': 'item de contrato',
                'verbose_name_plural': 'itens de contrato',
                'ordering': ['asset_code_snapshot'],
            },
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='contract_positive_period'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount_snapshot__gte', 0)), name='contract_non_negative_total'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PREPARED', 'ACTIVE', 'COMPLETED'])), name='contract_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('activated_at__isnull', True), ('completed_at__isnull', True), ('status', 'PREPARED')), models.Q(('activated_at__isnull', False), ('completed_at__isnull', True), ('status', 'ACTIVE')), models.Q(('activated_at__isnull', False), ('completed_at__isnull', False), ('status', 'COMPLETED')), _connector='OR'), name='contract_status_timestamp_consistency'),
        ),
        migrations.AddConstraint(
            model_name='contractitem',
            constraint=models.UniqueConstraint(fields=('contract', 'tool_unit'), name='unique_tool_unit_per_contract'),
        ),
        migrations.AddConstraint(
            model_name='contractitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('checked_out_at__isnull', True), ('checked_out_by__isnull', True), ('return_condition', ''), ('returned_at__isnull', True), ('returned_by__isnull', True)), models.Q(('checked_out_at__isnull', False), ('checked_out_by__isnull', False), ('return_condition', ''), ('returned_at__isnull', True), ('returned_by__isnull', True)), models.Q(('checked_out_at__isnull', False), ('checked_out_by__isnull', False), ('return_condition__in', ['AVAILABLE', 'INSPECTION', 'MAINTENANCE', 'DAMAGED', 'LOST']), ('returned_at__isnull', False), ('returned_by__isnull', False)), _connector='OR'), name='contract_item_event_consistency'),
        ),
    ]
