# Generated by Django 5.2.16 on 2026-08-29 15:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('organizations', '0002_establishment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractOffering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offering_name', models.CharField(max_length=160, verbose_name='nome do adicional')),
                ('kind', models.CharField(max_length=16, verbose_name='categoria')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantidade')),
                ('price_effect', models.CharField(max_length=8, verbose_name='efeito no preço')),
                ('line_total_snapshot', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='total do adicional')),
                ('requires_preparation', models.BooleanField(default=False, verbose_name='exige preparação técnica')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='contracts.contract')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_offerings', to='organizations.organization')),
            ],
        ),
    ]
