# Generated by Django 5.2.16 on 2026-08-29 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contractoffering'),
        ('reservations', '0002_reservationallocation_quotation_item_offering_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractoffering',
            name='reservation_offering',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contract_offering', to='reservations.reservationoffering'),
        ),
        migrations.AddField(
            model_name='contractitem',
            name='contract_offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='physical_items', to='contracts.contractoffering'),
        ),
        migrations.AddConstraint(
            model_name='contractoffering',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='contract_offering_positive_quantity'),
        ),
        migrations.AddConstraint(
            model_name='contractoffering',
            constraint=models.CheckConstraint(condition=models.Q(('line_total_snapshot__gte', 0)), name='contract_offering_non_negative_total'),
        ),
        migrations.AddConstraint(
            model_name='contractoffering',
            constraint=models.CheckConstraint(condition=models.Q(('price_effect__in', ['ADDITION', 'DISCOUNT'])), name='contract_offering_valid_effect'),
        ),
        migrations.AddConstraint(
            model_name='contractoffering',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['CONFIGURATION', 'RETURNABLE', 'CONSUMABLE', 'SERVICE', 'REMOVAL'])), name='contract_offering_valid_kind'),
        ),
    ]
