# Generated by Django 5.2.16 on 2026-08-26 00:44

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import uuid
from django.db import migrations, models


def create_postgresql_exclusion(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    table = schema_editor.quote_name("reservations_reservationallocation")
    constraint = schema_editor.quote_name("prevent_overlapping_active_reservations")
    schema_editor.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    schema_editor.execute(
        f"ALTER TABLE {table} ADD CONSTRAINT {constraint} "
        "EXCLUDE USING GIST ("
        "tool_unit_id WITH =, "
        "TSTZRANGE(starts_at, ends_at, '[)') WITH &&"
        ") WHERE (released_at IS NULL)"
    )


def drop_postgresql_exclusion(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    table = schema_editor.quote_name("reservations_reservationallocation")
    constraint = schema_editor.quote_name("prevent_overlapping_active_reservations")
    schema_editor.execute(f"ALTER TABLE {table} DROP CONSTRAINT IF EXISTS {constraint}")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_alter_toolunit_options_assetcodesequence'),
        ('organizations', '0002_establishment'),
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField(verbose_name='início da reserva')),
                ('ends_at', models.DateTimeField(verbose_name='fim da reserva')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmada'), ('CANCELLED', 'Cancelada')], default='CONFIRMED', max_length=10, verbose_name='situação')),
                ('confirmed_at', models.DateTimeField(verbose_name='confirmada em')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelada em')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='organizations.establishment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='organizations.organization')),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='quotations.quotation')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField(verbose_name='início reservado')),
                ('ends_at', models.DateTimeField(verbose_name='fim reservado')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='liberada em')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_allocations', to='organizations.organization')),
                ('quotation_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_allocations', to='quotations.quotationitem')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='reservations.reservation')),
                ('tool_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_allocations', to='catalog.toolunit')),
            ],
            options={
                'verbose_name': 'alocação de reserva',
                'verbose_name_plural': 'alocações de reserva',
                'ordering': ['tool_unit__asset_code'],
            },
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='reservation_positive_period'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['CONFIRMED', 'CANCELLED'])), name='reservation_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancelled_at__isnull', True), ('status', 'CONFIRMED')), models.Q(('cancelled_at__isnull', False), ('status', 'CANCELLED')), _connector='OR'), name='reservation_status_timestamp_consistency'),
        ),
        migrations.AddConstraint(
            model_name='reservationallocation',
            constraint=models.UniqueConstraint(fields=('reservation', 'tool_unit'), name='unique_tool_unit_per_reservation'),
        ),
        migrations.AddConstraint(
            model_name='reservationallocation',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='reservation_allocation_positive_period'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    create_postgresql_exclusion,
                    reverse_code=drop_postgresql_exclusion,
                ),
            ],
            state_operations=[
                migrations.AddConstraint(
                    model_name='reservationallocation',
                    constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('released_at__isnull', True)), expressions=[('tool_unit', '='), (models.Func(models.F('starts_at'), models.F('ends_at'), models.Value('[)'), function='TSTZRANGE', output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField()), '&&')], name='prevent_overlapping_active_reservations'),
                ),
            ],
        ),
    ]
