# Generated by Django 5.2.16 on 2026-08-29 15:09

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_establishment'),
        ('quotations', '0002_quotation_rental_notes_quotationitemoffering'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='reservationallocation',
                    name='prevent_overlapping_active_reservations',
                ),
            ],
        ),
        migrations.AddField(
            model_name='reservationallocation',
            name='quotation_item_offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation_allocations', to='quotations.quotationitemoffering'),
        ),
        migrations.CreateModel(
            name='ReservationOffering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offering_name', models.CharField(max_length=160, verbose_name='nome do adicional')),
                ('kind', models.CharField(max_length=16, verbose_name='categoria')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantidade')),
                ('reserved_at', models.DateTimeField(verbose_name='reservado em')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='consumido em')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='liberado em')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_offerings', to='organizations.organization')),
                ('quotation_item_offering', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_offering', to='quotations.quotationitemoffering')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='reservations.reservation')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='reservation_offering_positive_quantity'), models.CheckConstraint(condition=models.Q(('consumed_at__isnull', False), ('released_at__isnull', False), _negated=True), name='reservation_offering_not_consumed_and_released'), models.CheckConstraint(condition=models.Q(('kind__in', ['CONFIGURATION', 'RETURNABLE', 'CONSUMABLE', 'SERVICE', 'REMOVAL'])), name='reservation_offering_valid_kind')],
            },
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddConstraint(
                    model_name='reservationallocation',
                    constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                        condition=models.Q(('released_at__isnull', True)),
                        expressions=[
                            ('tool_unit', '='),
                            (
                                models.Func(
                                    models.F('starts_at'),
                                    models.F('ends_at'),
                                    models.Value('[)'),
                                    function='TSTZRANGE',
                                    output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                                ),
                                '&&',
                            ),
                        ],
                        name='prevent_overlapping_active_reservations',
                    ),
                ),
            ],
        ),
    ]
