# Generated by Django 5.2.16 on 2026-08-12

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0006_alter_toolunit_options_assetcodesequence"),
        ("customers", "0001_initial"),
        ("organizations", "0002_establishment"),
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("starts_at", models.DateTimeField(verbose_name="início da locação")),
                ("ends_at", models.DateTimeField(verbose_name="fim da locação")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Rascunho"),
                            ("SENT", "Enviado"),
                            ("EXPIRED", "Expirado"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        default="DRAFT",
                        max_length=10,
                        verbose_name="situação",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="valor total",
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True, verbose_name="enviado em")),
                (
                    "expired_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="expirado em"),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="cancelado em"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotations",
                        to="customers.customer",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotations",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "orçamento",
                "verbose_name_plural": "orçamentos",
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                        name="quotation_positive_period",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("total_amount__gte", 0)),
                        name="quotation_non_negative_total",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["DRAFT", "SENT", "EXPIRED", "CANCELLED"])
                        ),
                        name="quotation_valid_status",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="QuotationItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "equipment_quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="quantidade de equipamentos",
                    ),
                ),
                (
                    "billing_unit",
                    models.CharField(
                        choices=[("HOUR", "Hora"), ("DAY", "Dia"), ("MONTH", "Mês")],
                        max_length=5,
                        verbose_name="unidade de cobrança",
                    ),
                ),
                (
                    "period_quantity",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.000001"))
                        ],
                        verbose_name="quantidade do período",
                    ),
                ),
                (
                    "billed_quantity",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.000001"))
                        ],
                        verbose_name="quantidade cobrada",
                    ),
                ),
                (
                    "unit_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="tarifa unitária",
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="total do item",
                    ),
                ),
                ("policy_effective_from", models.DateField(verbose_name="vigência do preço")),
                (
                    "partial_unit_rounding",
                    models.CharField(
                        choices=[
                            ("UP", "Arredondar para cima"),
                            ("PROPORTIONAL", "Cobrança proporcional"),
                        ],
                        max_length=12,
                        verbose_name="regra de fração",
                    ),
                ),
                (
                    "month_definition",
                    models.CharField(
                        choices=[
                            ("FIXED_DAYS", "Quantidade fixa de dias"),
                            ("CALENDAR_MONTH", "Mês-calendário"),
                        ],
                        max_length=14,
                        verbose_name="definição de mês",
                    ),
                ),
                (
                    "fixed_month_days",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="dias do mês fixo",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotation_items",
                        to="organizations.organization",
                    ),
                ),
                (
                    "pricing_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotation_items",
                        to="pricing.pricingpolicy",
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="quotations.quotation",
                    ),
                ),
                (
                    "tool_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotation_items",
                        to="catalog.toolmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "item de orçamento",
                "verbose_name_plural": "itens de orçamento",
                "ordering": ["created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("quotation", "tool_model", "billing_unit"),
                        name="unique_quotation_model_billing_unit",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("equipment_quantity__gte", 1)),
                        name="quotation_item_positive_equipment_quantity",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("period_quantity__gt", 0)),
                        name="quotation_item_positive_period_quantity",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("billed_quantity__gt", 0)),
                        name="quotation_item_positive_billed_quantity",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("unit_rate__gte", 0)),
                        name="quotation_item_non_negative_rate",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("line_total__gte", 0)),
                        name="quotation_item_non_negative_total",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("billing_unit__in", ["HOUR", "DAY", "MONTH"])),
                        name="quotation_item_valid_billing_unit",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("partial_unit_rounding__in", ["UP", "PROPORTIONAL"])
                        ),
                        name="quotation_item_valid_rounding",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                ("fixed_month_days__gte", 1),
                                ("fixed_month_days__isnull", False),
                                ("fixed_month_days__lte", 366),
                                ("month_definition", "FIXED_DAYS"),
                            )
                            | models.Q(
                                ("fixed_month_days__isnull", True),
                                ("month_definition", "CALENDAR_MONTH"),
                            )
                        ),
                        name="quotation_item_valid_month_definition",
                    ),
                ],
            },
        ),
    ]
