# Generated by Django 5.2.16 on 2026-08-29 15:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_toolunit_status'),
        ('offerings', '0001_initial'),
        ('organizations', '0002_establishment'),
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='rental_notes',
            field=models.TextField(blank=True, help_text='Texto livre sem efeito automático em preço, estoque ou disponibilidade.', verbose_name='observações da locação'),
        ),
        migrations.CreateModel(
            name='QuotationItemOffering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offering_name', models.CharField(max_length=160, verbose_name='nome do adicional')),
                ('kind', models.CharField(max_length=16, verbose_name='categoria')),
                ('price_effect', models.CharField(choices=[('ADDITION', 'Acréscimo'), ('DISCOUNT', 'Desconto')], max_length=8, verbose_name='efeito no preço')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantidade')),
                ('billing_method', models.CharField(max_length=10, verbose_name='forma de cobrança')),
                ('billing_unit', models.CharField(blank=True, max_length=5, verbose_name='unidade de cobrança')),
                ('billed_quantity', models.DecimalField(decimal_places=6, max_digits=14, verbose_name='quantidade cobrada')),
                ('unit_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='tarifa unitária')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='total')),
                ('policy_effective_from', models.DateField(verbose_name='vigência do preço')),
                ('requires_preparation', models.BooleanField(default=False, verbose_name='exige preparação técnica')),
                ('inventory_tool_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_offering_snapshots', to='catalog.toolmodel')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_selections', to='offerings.offering')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_item_offerings', to='organizations.organization')),
                ('pricing_policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_selections', to='offerings.offeringpricingpolicy')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='quotations.quotation')),
                ('quotation_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='quotations.quotationitem')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('quotation_item', 'offering'), name='unique_offering_per_quotation_item'), models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='quotation_offering_positive_quantity'), models.CheckConstraint(condition=models.Q(('billed_quantity__gt', 0)), name='quotation_offering_positive_billed_quantity'), models.CheckConstraint(condition=models.Q(('line_total__gte', 0), ('unit_rate__gte', 0)), name='quotation_offering_non_negative_values'), models.CheckConstraint(condition=models.Q(('price_effect__in', ['ADDITION', 'DISCOUNT'])), name='quotation_offering_valid_effect'), models.CheckConstraint(condition=models.Q(('kind__in', ['CONFIGURATION', 'RETURNABLE', 'CONSUMABLE', 'SERVICE', 'REMOVAL'])), name='quotation_offering_valid_kind')],
            },
        ),
    ]
