# Generated by Django 5.2.16 on 2026-10-08 23:02

import apps.inspections.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0003_contractoffering_reservation_offering_and_more'),
        ('organizations', '0002_establishment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('COMPLETED', 'Concluída')], default='DRAFT', max_length=10, verbose_name='situação')),
                ('general_notes', models.TextField(blank=True, verbose_name='observações gerais')),
                ('customer_acknowledged', models.BooleanField(default=False, verbose_name='cliente acompanhou a conferência')),
                ('customer_representative_name', models.CharField(blank=True, max_length=200, verbose_name='nome de quem acompanhou')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_outbound_inspections', to=settings.AUTH_USER_MODEL)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_inspection', to='contracts.contract')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_outbound_inspections', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_inspections', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'inspeção inicial',
                'verbose_name_plural': 'inspeções iniciais',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutboundInspectionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_code_snapshot', models.CharField(max_length=50, verbose_name='código do equipamento')),
                ('tool_name_snapshot', models.CharField(max_length=260, verbose_name='equipamento')),
                ('condition', models.CharField(blank=True, choices=[('EXCELLENT', 'Excelente'), ('GOOD', 'Boa'), ('FAIR', 'Desgaste aparente'), ('DAMAGED', 'Avaria preexistente')], max_length=16, verbose_name='condição externa')),
                ('functional_result', models.CharField(choices=[('PENDING', 'Não testado'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Reprovado')], default='PENDING', max_length=10, verbose_name='teste funcional')),
                ('cleanliness_confirmed', models.BooleanField(default=False, verbose_name='limpeza conferida')),
                ('safety_confirmed', models.BooleanField(default=False, verbose_name='segurança conferida')),
                ('components_snapshot', models.TextField(blank=True, verbose_name='componentes e acessórios entregues')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('contract_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_inspection_item', to='contracts.contractitem')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspections.outboundinspection')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_inspection_items', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'item da inspeção inicial',
                'verbose_name_plural': 'itens da inspeção inicial',
                'ordering': ['asset_code_snapshot'],
            },
        ),
        migrations.CreateModel(
            name='InspectionEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=apps.inspections.models.inspection_evidence_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'pdf']), apps.inspections.models.validate_evidence_size], verbose_name='arquivo')),
                ('original_name', models.CharField(max_length=255, verbose_name='nome original')),
                ('content_type', models.CharField(max_length=100, verbose_name='tipo de conteúdo')),
                ('size_bytes', models.PositiveIntegerField(verbose_name='tamanho em bytes')),
                ('sha256', models.CharField(max_length=64, verbose_name='SHA-256')),
                ('caption', models.CharField(blank=True, max_length=240, verbose_name='descrição')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_evidences', to='organizations.organization')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_inspection_evidences', to=settings.AUTH_USER_MODEL)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='inspections.outboundinspection')),
                ('inspection_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='inspections.outboundinspectionitem')),
            ],
            options={
                'verbose_name': 'evidência de inspeção',
                'verbose_name_plural': 'evidências de inspeção',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='outboundinspection',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'COMPLETED'])), name='outbound_inspection_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='outboundinspection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('completed_by__isnull', True), ('status', 'DRAFT')), models.Q(('completed_at__isnull', False), ('completed_by__isnull', False), ('customer_acknowledged', True), ('status', 'COMPLETED')), _connector='OR'), name='outbound_inspection_status_consistency'),
        ),
        migrations.AddConstraint(
            model_name='outboundinspectionitem',
            constraint=models.CheckConstraint(condition=models.Q(('condition__in', ['', 'EXCELLENT', 'GOOD', 'FAIR', 'DAMAGED'])), name='outbound_item_valid_condition'),
        ),
        migrations.AddConstraint(
            model_name='outboundinspectionitem',
            constraint=models.CheckConstraint(condition=models.Q(('functional_result__in', ['PENDING', 'APPROVED', 'REJECTED'])), name='outbound_item_valid_functional_result'),
        ),
        migrations.AddConstraint(
            model_name='inspectionevidence',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gte', 1)), name='inspection_evidence_positive_size'),
        ),
    ]
