# Generated by Django 5.2.16 on 2026-07-11 19:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('active', models.BooleanField(default=True, verbose_name='ativa')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'categoria',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ToolModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='marca')),
                ('model_number', models.CharField(blank=True, max_length=100, verbose_name='modelo')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor da diária')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor da caução')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tool_models', to='catalog.category')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_models', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'modelo de ferramenta',
                'verbose_name_plural': 'modelos de ferramentas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ToolUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_code', models.CharField(max_length=50, verbose_name='código patrimonial')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='número de série')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponível'), ('RESERVED', 'Reservada'), ('RENTED', 'Alugada'), ('INSPECTION', 'Em inspeção'), ('MAINTENANCE', 'Em manutenção'), ('DAMAGED', 'Danificada'), ('INACTIVE', 'Inativa')], default='AVAILABLE', max_length=16)),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='localização')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_units', to='organizations.organization')),
                ('tool_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='catalog.toolmodel')),
            ],
            options={
                'verbose_name': 'unidade de ferramenta',
                'verbose_name_plural': 'unidades de ferramentas',
                'ordering': ['asset_code'],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_category_name_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='toolmodel',
            constraint=models.UniqueConstraint(fields=('organization', 'name', 'brand', 'model_number'), name='unique_tool_model_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='toolunit',
            constraint=models.UniqueConstraint(fields=('organization', 'asset_code'), name='unique_asset_code_per_organization'),
        ),
    ]
