# Generated by Django 5.2.16 on 2026-07-18 02:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('organizations', '0002_establishment'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolunit',
            name='establishment',
            field=models.ForeignKey(blank=True, help_text='Estabelecimento responsável pela unidade física.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tool_units', to='organizations.establishment'),
        ),
        migrations.AlterField(
            model_name='toolmodel',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='valor da diária'),
        ),
        migrations.AlterField(
            model_name='toolmodel',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='valor da caução'),
        ),
        migrations.AddConstraint(
            model_name='toolmodel',
            constraint=models.CheckConstraint(condition=models.Q(('daily_rate__gte', 0)), name='non_negative_daily_rate'),
        ),
        migrations.AddConstraint(
            model_name='toolmodel',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_amount__gte', 0)), name='non_negative_deposit_amount'),
        ),
    ]
