# Generated by Django 5.2.16 on 2026-08-11 02:08

import django.db.models.deletion
import re
import uuid
from django.db import migrations, models


ASSET_CODE_PATTERN = re.compile(r'^EQ-(\d+)$')


def initialize_asset_code_sequences(apps, schema_editor):
    AssetCodeSequence = apps.get_model('catalog', 'AssetCodeSequence')
    ToolUnit = apps.get_model('catalog', 'ToolUnit')

    organization_ids = (
        ToolUnit.objects.order_by()
        .values_list('organization_id', flat=True)
        .distinct()
    )
    for organization_id in organization_ids.iterator():
        highest_value = 0
        asset_codes = ToolUnit.objects.filter(
            organization_id=organization_id,
            asset_code__startswith='EQ-',
        ).values_list('asset_code', flat=True)
        for asset_code in asset_codes.iterator():
            match = ASSET_CODE_PATTERN.fullmatch(asset_code)
            if match:
                highest_value = max(highest_value, int(match.group(1)))
        if highest_value:
            AssetCodeSequence.objects.create(
                organization_id=organization_id,
                next_value=highest_value + 1,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_toolmodel_daily_rate'),
        ('organizations', '0002_establishment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolunit',
            options={'ordering': ['asset_code'], 'verbose_name': 'equipamento físico', 'verbose_name_plural': 'equipamentos físicos'},
        ),
        migrations.CreateModel(
            name='AssetCodeSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('next_value', models.PositiveBigIntegerField(default=1, verbose_name='próximo número')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asset_code_sequence', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'sequência de códigos internos',
                'verbose_name_plural': 'sequências de códigos internos',
                'constraints': [models.CheckConstraint(condition=models.Q(('next_value__gte', 1)), name='positive_asset_code_next_value')],
            },
        ),
        migrations.RunPython(
            initialize_asset_code_sequences,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
