# Generated by Django 5.2.16 on 2026-08-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_toolunit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolunit',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Apta para locação'), ('RESERVED', 'Reservada'), ('RENTED', 'Alugada'), ('INSPECTION', 'Em inspeção'), ('MAINTENANCE', 'Em manutenção'), ('DAMAGED', 'Danificada'), ('LOST', 'Perdida'), ('INACTIVE', 'Inativa')], default='AVAILABLE', max_length=16),
        ),
    ]
