# Generated by Django 5.2.16 on 2026-08-29 15:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0008_alter_toolunit_status'),
        ('organizations', '0002_establishment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('kind', models.CharField(choices=[('CONFIGURATION', 'Configuração'), ('RETURNABLE', 'Acessório retornável'), ('CONSUMABLE', 'Consumível'), ('SERVICE', 'Serviço'), ('REMOVAL', 'Remoção com desconto')], max_length=16, verbose_name='categoria')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('requires_preparation', models.BooleanField(default=False, verbose_name='exige preparação técnica')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('inventory_tool_model', models.ForeignKey(blank=True, help_text='Modelo físico reservado para esta configuração ou acessório.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_offerings', to='catalog.toolmodel')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'adicional configurável',
                'verbose_name_plural': 'adicionais configuráveis',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OfferingCompatibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_quantity_per_equipment', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantidade máxima por equipamento')),
                ('active', models.BooleanField(default=True, verbose_name='ativa')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='offerings.offering')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offering_compatibilities', to='organizations.organization')),
                ('tool_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offering_compatibilities', to='catalog.toolmodel')),
            ],
            options={
                'ordering': ['tool_model__name', 'offering__name'],
            },
        ),
        migrations.CreateModel(
            name='OfferingPricingPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate, verbose_name='vigente a partir de')),
                ('billing_method', models.CharField(choices=[('FLAT', 'Valor único por locação'), ('PER_PERIOD', 'Por período')], default='FLAT', max_length=10, verbose_name='forma de cobrança')),
                ('flat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='valor único')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='valor por hora')),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='valor por dia')),
                ('monthly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='valor por mês')),
                ('active', models.BooleanField(default=True, verbose_name='ativa')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_policies', to='offerings.offering')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offering_pricing_policies', to='organizations.organization')),
            ],
            options={
                'ordering': ['offering__name', '-effective_from', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferingStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('on_hand_quantity', models.PositiveIntegerField(default=0, verbose_name='quantidade em estoque')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, verbose_name='quantidade reservada')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offering_stocks', to='organizations.establishment')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='offerings.offering')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offering_stocks', to='organizations.organization')),
            ],
        ),
        migrations.AddConstraint(
            model_name='offering',
            constraint=models.UniqueConstraint(fields=('organization', 'name', 'kind'), name='unique_offering_name_kind_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='offering',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('inventory_tool_model__isnull', False), ('kind', 'RETURNABLE')), ('kind', 'CONFIGURATION'), models.Q(('inventory_tool_model__isnull', True), ('kind__in', ['CONSUMABLE', 'SERVICE', 'REMOVAL'])), _connector='OR'), name='offering_inventory_kind_consistency'),
        ),
        migrations.AddConstraint(
            model_name='offering',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['CONFIGURATION', 'RETURNABLE', 'CONSUMABLE', 'SERVICE', 'REMOVAL'])), name='offering_valid_kind'),
        ),
        migrations.AddConstraint(
            model_name='offeringcompatibility',
            constraint=models.UniqueConstraint(fields=('offering', 'tool_model'), name='unique_offering_compatibility'),
        ),
        migrations.AddConstraint(
            model_name='offeringcompatibility',
            constraint=models.CheckConstraint(condition=models.Q(('max_quantity_per_equipment__gte', 1)), name='positive_offering_max_quantity'),
        ),
        migrations.AddConstraint(
            model_name='offeringpricingpolicy',
            constraint=models.UniqueConstraint(fields=('offering', 'effective_from'), name='unique_offering_price_version'),
        ),
        migrations.AddConstraint(
            model_name='offeringpricingpolicy',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('billing_method', 'FLAT'), ('daily_rate__isnull', True), ('flat_amount__isnull', False), ('hourly_rate__isnull', True), ('monthly_rate__isnull', True)), models.Q(('billing_method', 'PER_PERIOD'), ('flat_amount__isnull', True)), _connector='OR'), name='offering_price_billing_consistency'),
        ),
        migrations.AddConstraint(
            model_name='offeringpricingpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('billing_method', 'FLAT'), ('hourly_rate__isnull', False), ('daily_rate__isnull', False), ('monthly_rate__isnull', False), _connector='OR'), name='offering_period_price_has_rate'),
        ),
        migrations.AddConstraint(
            model_name='offeringpricingpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('billing_method__in', ['FLAT', 'PER_PERIOD'])), name='offering_price_valid_billing_method'),
        ),
        migrations.AddConstraint(
            model_name='offeringstock',
            constraint=models.UniqueConstraint(fields=('offering', 'establishment'), name='unique_offering_stock_per_establishment'),
        ),
        migrations.AddConstraint(
            model_name='offeringstock',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__lte', models.F('on_hand_quantity'))), name='offering_reserved_not_above_stock'),
        ),
    ]
