# Generated by Django 5.2.16 on 2026-08-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerings', '0001_initial'),
        ('organizations', '0002_establishment'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='offeringpricingpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('flat_amount__gte', 0), ('flat_amount__isnull', True), _connector='OR'), name='offering_price_non_negative_flat'),
        ),
        migrations.AddConstraint(
            model_name='offeringpricingpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('hourly_rate__gte', 0), ('hourly_rate__isnull', True), _connector='OR'), name='offering_price_non_negative_hourly'),
        ),
        migrations.AddConstraint(
            model_name='offeringpricingpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('daily_rate__gte', 0), ('daily_rate__isnull', True), _connector='OR'), name='offering_price_non_negative_daily'),
        ),
        migrations.AddConstraint(
            model_name='offeringpricingpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_rate__gte', 0), ('monthly_rate__isnull', True), _connector='OR'), name='offering_price_non_negative_monthly'),
        ),
    ]
