# Generated by Django 5.2.16 on 2026-07-18 02:22

import common.documents
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('cnpj', models.CharField(blank=True, help_text='Aceita CNPJ numérico ou alfanumérico, com ou sem máscara.', max_length=18, null=True, unique=True, validators=[common.documents.validate_cnpj], verbose_name='CNPJ')),
                ('kind', models.CharField(choices=[('HEADQUARTERS', 'Matriz'), ('BRANCH', 'Filial')], default='HEADQUARTERS', max_length=12, verbose_name='tipo')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establishments', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'estabelecimento',
                'verbose_name_plural': 'estabelecimentos',
                'ordering': ['organization__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'name'), name='unique_establishment_name_per_organization'), models.UniqueConstraint(condition=models.Q(('active', True), ('kind', 'HEADQUARTERS')), fields=('organization',), name='unique_active_headquarters_per_organization'), models.CheckConstraint(condition=models.Q(('cnpj__isnull', True), ('cnpj__regex', '^[A-Z0-9]{12}[0-9]{2}$'), _connector='OR'), name='normalized_cnpj_format')],
            },
        ),
    ]
